module.exports = {
    Authentication: 'Authentication',
    Data: 'Data',
    Devices: 'Devices',
    GeoFenceDeviceLookup: 'GeoFenceDeviceLookup',
    GeoFencePolygons: 'GeoFencePolygons',
    GeoFences: 'GeoFences',
    GeoFenceUserLookup: 'GeoFenceUserLookup',
    PermissionIndex: 'PermissionIndex',
    Permissions: 'Permissions',
    SessionTokens: 'SessionTokens',
    Groups: 'Groups',
    Protocols: 'Protocols',
    SensorAttributes: 'SensorAttributes',
    SensorGroups: 'SensorGroups',
    SensorProtocols: 'SensorProtocols',
    Sensors: 'Sensors',
    DeviceAttributeData: 'DeviceAttributeData',
    Attributes: 'Attributes',
    BussinessUnits: 'BussinessUnits',
    ResetPasswordTokens: 'ResetPasswordTokens',
};