POST http://localhost:443/api/v1/auth/login
Content-Type: application/json

{
    "username": "Luke",
    "password": "Damian64"
}

###

POST http://localhost:443/api/v1/auth/refresh_token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTYxMTczOTk4NSwiZXhwIjoxNjExNzQwODg1fQ.TmOWDl4lmAi7EbUedKQSWqp8SkZGtg6A6pQmh5PX2g21AVfPElYLYt-_KZ2tm6grZBL-nAT5g84lSLltfkXE2XDmND-ld_gUDfdefv5RkxECLc1ykpnAtUv_5_KTjoVjID5gVXDkE2Z_jNmLMYOKz3vuybzcdzWpE5tc0B2_tSRCZhUKSH7iLezu26ISbugquSrLaZt_KNMWGU-y-YOolyDOSUxdEwLQz7Ck4hYQeu0kJWIzZJ0lz-sam6a6GZI_yLUuWl8gbrufQBQUptVXUuyBJKLz96K2wUt54mLFSaO4MhfUsXPGkxmxzavcFwcNKlWKMrAaKTgTNm-ZtkdgQA

{
    "username": "Luke",
    "password": "Damian64",
    "newpassword": "Damian64"
}

###

POST http://localhost:443/api/v1/accounts/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTYxMTczOTk4NSwiZXhwIjoxNjExNzQwODg1fQ.TmOWDl4lmAi7EbUedKQSWqp8SkZGtg6A6pQmh5PX2g21AVfPElYLYt-_KZ2tm6grZBL-nAT5g84lSLltfkXE2XDmND-ld_gUDfdefv5RkxECLc1ykpnAtUv_5_KTjoVjID5gVXDkE2Z_jNmLMYOKz3vuybzcdzWpE5tc0B2_tSRCZhUKSH7iLezu26ISbugquSrLaZt_KNMWGU-y-YOolyDOSUxdEwLQz7Ck4hYQeu0kJWIzZJ0lz-sam6a6GZI_yLUuWl8gbrufQBQUptVXUuyBJKLz96K2wUt54mLFSaO4MhfUsXPGkxmxzavcFwcNKlWKMrAaKTgTNm-ZtkdgQA

{
    "username": "Luke",
    "password": "Damian64",
    "newpassword": "Damian64"
}